### ISSUE TITLE
Can't make AppVeyor skip vc9

### ISSUE THREAD

**Issue by guyer** [conda-forge/pysparse-feedstock#2]
PySparse is incompatible with VC9. It's also incompatible with Py3k. 

When I skip these, [the appveyor build gets removed completely](https://github.com/conda-forge/pysparse-feedstock/pull/1/commits/f618f1483ff0d9f589c46eb64ba8aaf6ee75dc2c). 
Unless it gets retained for no obvious reason, but [still builds VC9 (and fails)](https://ci.appveyor.com/project/conda-forge/pysparse-feedstock/builds/19373996).

I've used the same selectors on the conda-forge/gmsh-feedstock and get a vc14 build the way I want.

@conda-forge/core: I need help

**Comment by isuruf** [comment]
Are you trying to compile a python 2.7 extension with vc14 ?

**Comment by guyer** [comment]
@isuruf yes, I am. I was not explicitly trying to build with vc14, but seemed to be getting things that insisted on it (yaml? Not something I directly require, but it says it's a [vc14] metapackage).

I just stripped out all of the earlier modifications I'd added to try to get the Windows version to build (it worked fine in staged-recipes, but the world broke when it became a real feedstock).

**Comment by isuruf** [comment]
openblas is not available on windows for vc14. You can try using mkl

**Comment by isuruf** [comment]
Sorry, openblas is not available on windows for vc9 (python 2.7)

**Comment by guyer** [comment]
At some point,  I got this to work with mkl
